### PR TITLE
Use deck name for deck/model identifiers

### PR DESCRIPTION
**Pull request by amorriscode**
_Note: This PR cannot be merged because it doesn't sync with Anki._

Following up on #40. It didn't resolve the issue because the top deck ID and model were still based on `Date.now()`. Therefore, Anki continued to add new cards when importing a generated deck.

-------

I did a quit test locally where the top deck ID is just a `sha1` of the deck name. Importing a deck once, then adding a card and importing again produced the following message:
```
Notes found in file: 17
Notes that could not be imported as note type has changed: 16
Notes added from file: 1
```
The duplicates don't come in, but the "note type" has changed. If you change a card, it comes in as a new card.

Because of this issue, I ended up making the following changes:
- [x] Generate a top deck GUID with a `sha1` of the deck name
- [x] Base the model ID off of the top deck GUID
- [x] Only use the front of the card for the card GUID

With these changes I'm able to:
- [x] Generate a deck and import it to Anki
- [x] Generate the same deck with new cards and import it to Anki without duplicates
- [x] Generate the same deck after updating the back of cards and import it to Anki with no issues

### CODE REVIEW

**Comment by amorriscode** [comment]
@ashlinchak this is a first pass after our discussion about GUIDs being based on `Date.now()`. I have not tested nested decks but have tested these changes with [mdanki](https://github.com/ashlinchak/mdanki).

**Comment by amorriscode** [comment]
I've attempted to convert the `sha1` result to integers so it can be synced to Anki but I get the following error:
```
sqlite3.OperationalError: unrecognized token: "67f994533a5d976eed69aeae05e381bf6fa851e8"
```

**Comment by ashlinchak** [comment]
@amorriscode I've checked your changes and it's working for me. 
But I'm not sure if this is a better solution for adding the ability to update cards within a deck. Maybe better would be to change `anki-apkg-export` API for accepting deck's `did`. E.g. `mdanki` could generate a timestamp and store this `did` in markdown as hidden field. In this case, a user even can change the markdown title without creating duplicates in Anki. Also, using this approach we'll keep the same interfaces in `anki-apkg-export` and Anki itself as Anki also generates `did` as a timestamp. What do you think?
cc @ewnd9

**Comment by amorriscode** [comment]
@ashlinchak I agree with you, I think another solution certainly needs to be devised. I will leave this PR open until @ewnd9 comments.

**Comment by ashlinchak** [comment]
@amorriscode I like your idea for generating note `guid` based only on `topDeckId` and `front`. It would allow a user to make updates in `back` side.

**Comment by xerosanyam** [comment]
Guys, thanks a lot for the hard work.
Just wanted to know, what workflow is everyone following to cope up with this issue until it is solved 😅

**Comment by amorriscode** [comment]
@xerosanyam not a great solution but I just moved over to using Mochi. 😞

**Comment by xero-james-kim** [comment]
I didn't make a PR because it was a dirty hack, but I "fixed" the issue that it wasn't syncing with Anki just by slicing the sha1 :p 

```javascript
  _getDeckGuid(deckName) {
    const hashBytes = sha1(deckName);
    const shortened = hashBytes.slice(0, 8); // otherwise we don't get int, we get something like 1.337874276105709e+42
    return parseInt(shortened, 16);
  }
```

Probably not the most ideal fix, but works for me as I don't have many decks and was looking for a quick fix. In case anyone wanted to just pull this branch to get mdanki working for them.

**Comment by tricktux** [comment]
@amorriscode @ashlinchak Hey Guys?! Any progress on this. I really like `MDAnki`, it would be great if we could work around this!

**Comment by amorriscode** [comment]
> @amorriscode @ashlinchak Hey Guys?! Any progress on this. I really like `MDAnki`, it would be great if we could work around this!

Just thought I'd reiterate what I did before: I moved to Mochi. I know it's not a great solution but I haven't looked back!

**Comment by tricktux** [comment]
Anybody else? @ashlinchak @xero-james-kim  What about that hack? This the only link missing to get to the ultimate Anki experience!!

**Comment by jazzandrock** [comment]
@tricktux before this gets merged, try https://github.com/Steve2955/md2apkg. It just worked for me

**Comment by tricktux** [comment]
@jazzandrock yes! I did find that application. It works very well.

**Pull request closed without merging**
